# This file has been generated by node2nix 6.0.0. Do not edit!

{nodeEnv, fetchurl, fetchgit}:

let
  sources = {
    "async-1.5.2" = {
      name = "async";
      packageName = "async";
      version = "1.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-1.5.2.tgz";
        sha1 = "ec6a61ae56480c0c3cb241c95618e20892f9672a";
      };
    };
    "lodash-4.14.1" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.14.1.tgz";
        sha1 = "5b5d0a516ad3d46e12012d7f59ad66a5659bf408";
      };
    };
    "minimist-1.2.0" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz";
        sha1 = "a35008b20f41383eec1fb914f4cd5df79a264284";
      };
    };
  };
  args = {
    name = "hopglass-server";
    packageName = "hopglass-server";
    version = "1.0.0";
    src = fetchgit {
      url = "https://github.com/hopglass/hopglass-server.git";
      rev = "57e289003bb5d58e33ef8796a080dc086ff994a4";
      sha256 = "02rhcb435faamn266z0qg71ffacv3xgdvs2b66gqrvj9kg0wd4wk";
    };
    dependencies = [
      sources."async-1.5.2"
      sources."lodash-4.14.1"
      sources."minimist-1.2.0"
    ];
    meta = {
      description = "Collect data from Freifunk networks and provide it in serveral formats";
      homepage = "https://github.com/hopglass/hopglass-server#readme";
      license = "AGPL-3.0";
    };
    production = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}
