# This file has been generated by node2nix 1.1.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "async-1.5.2" = {
      name = "async";
      packageName = "async";
      version = "1.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-1.5.2.tgz";
        sha1 = "ec6a61ae56480c0c3cb241c95618e20892f9672a";
      };
    };
    "lodash-4.16.4" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.16.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.16.4.tgz";
        sha1 = "01ce306b9bad1319f2a5528674f88297aeb70127";
      };
    };
    "minimist-1.2.0" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz";
        sha1 = "a35008b20f41383eec1fb914f4cd5df79a264284";
      };
    };
  };
  args = rec {
    name = "hopglass-server";
    packageName = "hopglass-server";
    version = "0.1.3";
    src = fetchgit {
      url = "https://github.com/hopglass/hopglass-server.git";
      rev = "refs/tags/v${version}";
      sha256 = "1h8c1c29j7shxwd6ck8pxdy3v5jbh19vmc906bql9mdnxjf1d0z0";
    };
    dependencies = [
      sources."async-1.5.2"
      sources."lodash-4.16.4"
      sources."minimist-1.2.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Collect data from Freifunk networks and provide it in serveral formats";
      homepage = "https://github.com/hopglass/hopglass-server#readme";
      license = "AGPL-3.0";
    };
    production = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}
